### ISSUE TITLE
单页pdf文件损坏

### ISSUE THREAD

**Issue by friedrica137** [52beijixing/cxstar-pdf-download#3]
以ruid=28646b70000035XXXX为例，程序生成一个文件夹后里面单页的pdf文件都打不开耶:-O

**Comment by 52beijixing** [comment]
> 以ruid=28646b70000035XXXX为例，程序生成一个文件夹后里面单页的pdf文件都打不开耶:-O

畅想之星对于矢量版图书增加了加密校验，已经更新了代码和程序，您可以下载最新的代码或者程序，尝试问题是否解决

**Comment by friedrica137** [comment]
> > 以ruid=28646b70000035XXXX为例，程序生成一个文件夹后里面单页的pdf文件都打不开耶:-O
> 
> 畅想之星对于矢量版图书增加了加密校验，已经更新了代码和程序，您可以下载最新的代码或者程序，尝试问题是否解决

问题顺利解决！谢谢！！（要是公布alipay code的话就可以请您一杯咖啦哈哈哈哈）
