### ISSUE TITLE
建议删除

### ISSUE THREAD

**Issue by Spel1er123** [52beijixing/cxstar-pdf-download#5]
你把人家52的东西发这里博眼球引人关注，有没有考虑过发出来就会见光死呢，或早或晚！

**Comment by 52beijixing** [comment]
> 你把人家52的东西发这里博眼球引人关注，有没有考虑过发出来就会见光死呢，或早或晚！

你搞笑呢嘛？无论是校对验证还是下载申请权限以及接口全都是我自己发现并实现的。怎么我自己写的东西就成吾爱破解的了？

**Comment by 52beijixing** [comment]
> 你把人家52的东西发这里博眼球引人关注，有没有考虑过发出来就会见光死呢，或早或晚！

麻烦你贴出吾爱的帖子地址，我来回复你的问题。

**Comment by 52beijixing** [comment]
> 你把人家52的东西发这里博眼球引人关注，有没有考虑过发出来就会见光死呢，或早或晚！

我不知道你为什么这么说，吾爱是有大佬有比我更好更全的代码和工具。但是在吾爱公开代码和工具的应该只有我一个。
如果是别人没有公开的方法和工具，我自己发现和实现就是从吾爱破解拿来的话，我真的无话可说。

![1](https://github.com/52beijixing/cxstar-pdf-download/assets/75174838/d2bae198-92bb-4079-9857-e8ee9bf4d177)
![2](https://github.com/52beijixing/cxstar-pdf-download/assets/75174838/9d575479-ae9e-4a9a-a5ba-a4f0b97277ff)
![3](https://github.com/52beijixing/cxstar-pdf-download/assets/75174838/ec42cc6c-3838-47c3-a392-9bed2e4405e6)

**Comment by Spel1er123** [comment]
是不是你写的这并不重要！你能写出来又不奇怪，就一个加密参数而已，52有人发过贴，链接我不贴，人家都是脱敏的，不像你，心怕人不知道，重要的是这东西你不该拿出来发，你想帮助人，到头来之后筑高下书的壁垒，对你对大家都没有好处，还弄成exe，exe使用没有任何门槛，人手一个，你觉得这样的日子能长久吗？要不你建议官方增加下载功能，或者你去每本书下面发你的GitHub链接来普度众生？造福？哈哈，有些人就喜欢发微博发小红书，发抖音引流，不说官方兴师问罪顺藤摸瓜人赃并获，树大招风的道理明白不，完全就是自掘坟墓啊，该低调还是低调啊！

**Comment by ShiinaKaze** [comment]
> 是不是你写的这并不重要！你能写出来又不奇怪，就一个加密参数而已，52有人发过贴，链接我不贴，人家都是脱敏的，不像你，心怕人不知道，重要的是这东西你不该拿出来发，你想帮助人，到头来之后筑高下书的壁垒，对你对大家都没有好处，还弄成exe，exe使用没有任何门槛，人手一个，你觉得这样的日子能长久吗？要不你建议官方增加下载功能，或者你去每本书下面发你的GitHub链接来普度众生？造福？哈哈，有些人就喜欢发微博发小红书，发抖音引流，不说官方兴师问罪顺藤摸瓜人赃并获，树大招风的道理明白不，完全就是自掘坟墓啊，该低调还是低调啊！

所以还是只讲方法比较好，工具就算了，是这个意思么。

**Comment by 52beijixing** [comment]
> > 是不是你写的这并不重要！你能写出来又不奇怪，就一个加密参数而已，52有人发过贴，链接我不贴，人家都是脱敏的，不像你，心怕人不知道，重要的是这东西你不该拿出来发，你想帮助人，到头来之后筑高下书的壁垒，对你对大家都没有好处，还弄成exe，exe使用没有任何门槛，人手一个，你觉得这样的日子能长久吗？要不你建议官方增加下载功能，或者你去每本书下面发你的GitHub链接来普度众生？造福？哈哈，有些人就喜欢发微博发小红书，发抖音引流，不说官方兴师问罪顺藤摸瓜人赃并获，树大招风的道理明白不，完全就是自掘坟墓啊，该低调还是低调啊！
> 
> 所以还是只讲方法比较好，工具就算了，是这个意思么。

如果他原来就掌握了这种下载方法，确实会不希望这种方法公开。并且确实对于大部分电脑用户来说，这个项目已经将下载方法降到了无门槛的程度，可能会导致传播，以至于该方法会被和谐。
对于我个人来说，我目前掌握两种下载方法，所以公开一种方法于我而言并没有什么问题。
至于他个人，我是理解其想法，恶心其做法。因为上来就是说我抄袭搬运，且在他明知该下载方法不具备技术难度的前提下。

**Comment by sci268** [comment]
别理他，支持你，52beijixing

**Comment by Spel1er123** [comment]
> > > 是不是你写的这并不重要！你能写出来又不奇怪，就一个加密参数而已，52有人发过贴，链接我不贴，人家都是脱敏的，不像你，心怕人不知道，重要的是这东西你不该拿出来发，你想帮助人，到头来之后筑高下书的壁垒，对你对大家都没有好处，还弄成exe，exe使用没有任何门槛，人手一个，你觉得这样的日子能长久吗？要不你建议官方增加下载功能，或者你去每本书下面发你的GitHub链接来普度众生？造福？哈哈，有些人就喜欢发微博发小红书，发抖音引流，不说官方兴师问罪顺藤摸瓜人赃并获，树大招风的道理明白不，完全就是自掘坟墓啊，该低调还是低调啊！
> > 
> > 
> > 所以还是只讲方法比较好，工具就算了，是这个意思么。
> 
> 如果他原来就掌握了这种下载方法，确实会不希望这种方法公开。并且确实对于大部分电脑用户来说，这个项目已经将下载方法降到了无门槛的程度，可能会导致传播，以至于该方法会被和谐。 对于我个人来说，我目前掌握两种下载方法，所以公开一种方法于我而言并没有什么问题。 至于他个人，我是理解其想法，恶心其做法。因为上来就是说我抄袭搬运，且在他明知该下载方法不具备技术难度的前提下。

是个人都知道什么该发什么不该发，那些见光死的资源不是少数，原因就是有人喜欢表现乱发，传播泛滥官方升级加固壁垒，你以为掌握几种方法就高枕无忧了，痴人说梦啊，说是几种方法，其实就一个源头，无所谓这话越听越像小白说出来的，你能不能下载取决于官方，你下载到什么质量的pdf也取决于官方，52会下载的人多的是，没见你这么表现的，这是能往GitHub发的吗，别总是觉得自己高尚，别人就自私，自欺欺人吧了，别别人一捧你，让你干什么你就使劲表现。

**Comment by sci268** [comment]
作者是个好人，大好人，相信他发出来完全一片好心。世事险恶，为作者考虑，还是删了吧。
没必要争执，没必要自寻烦恼，前车之鉴确实不少。阿弥陀佛



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月16日 18:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [52beijixing/cxstar-pdf-download] 建议删除 (Issue #5) |

是不是你写的这并不重要！你能写出来又不奇怪，就一个加密参数而已，52有人发过贴，链接我不贴，人家都是脱敏的，不像你，心怕人不知道，重要的是这东西你不该拿出来发，你想帮助人，到头来之后筑高下书的壁垒，对你对大家都没有好处，还弄成exe，exe使用没有任何门槛，人手一个，你觉得这样的日子能长久吗？要不你建议官方增加下载功能，或者你去每本书下面发你的GitHub链接来普度众生？造福？哈哈，有些人就喜欢发微博发小红书，发抖音引流，不说官方兴师问罪顺藤摸瓜人赃并获，树大招风的道理明白不，完全就是自掘坟墓啊，该低调还是低调啊！

所以还是只讲方法比较好，工具就算了，是这个意思么。

如果他原来就掌握了这种下载方法，确实会不希望这种方法公开。并且确实对于大部分电脑用户来说，这个项目已经将下载方法降到了无门槛的程度，可能会导致传播，以至于该方法会被和谐。 对于我个人来说，我目前掌握两种下载方法，所以公开一种方法于我而言并没有什么问题。 至于他个人，我是理解其想法，恶心其做法。因为上来就是说我抄袭搬运，且在他明知该下载方法不具备技术难度的前提下。

是个人都知道什么该发什么不该发，那些见光死的资源不是少数，原因就是有人喜欢表现乱发，传播泛滥官方升级加固壁垒，你以为掌握几种方法就高枕无忧了，痴人说梦啊，说是几种方法，其实就一个源头，无所谓这话越听越像小白说出来的，你能不能下载取决于官方，你下载到什么质量的pdf也取决于官方，52会下载的人多的是，没见你这么表现的，这是能往GitHub发的吗，别总是觉得自己高尚，别人就自私，自欺欺人吧了，别别人一捧你，让你干什么你就使劲表现。

**Comment by 52beijixing** [comment]
> > > > 是不是你写的这并不重要！你能写出来又不奇怪，就一个加密参数而已，52有人发过贴，链接我不贴，人家都是脱敏的，不像你，心怕人不知道，重要的是这东西你不该拿出来发，你想帮助人，到头来之后筑高下书的壁垒，对你对大家都没有好处，还弄成exe，exe使用没有任何门槛，人手一个，你觉得这样的日子能长久吗？要不你建议官方增加下载功能，或者你去每本书下面发你的GitHub链接来普度众生？造福？哈哈，有些人就喜欢发微博发小红书，发抖音引流，不说官方兴师问罪顺藤摸瓜人赃并获，树大招风的道理明白不，完全就是自掘坟墓啊，该低调还是低调啊！
> > > 
> > > 
> > > 所以还是只讲方法比较好，工具就算了，是这个意思么。
> > 
> > 
> > 如果他原来就掌握了这种下载方法，确实会不希望这种方法公开。并且确实对于大部分电脑用户来说，这个项目已经将下载方法降到了无门槛的程度，可能会导致传播，以至于该方法会被和谐。 对于我个人来说，我目前掌握两种下载方法，所以公开一种方法于我而言并没有什么问题。 至于他个人，我是理解其想法，恶心其做法。因为上来就是说我抄袭搬运，且在他明知该下载方法不具备技术难度的前提下。
> 
> 是个人都知道什么该发什么不该发，那些见光死的资源不是少数，原因就是有人喜欢表现乱发，传播泛滥官方升级加固壁垒，你以为掌握几种方法就高枕无忧了，痴人说梦啊，说是几种方法，其实就一个源头，无所谓这话越听越像小白说出来的，你能不能下载取决于官方，你下载到什么质量的pdf也取决于官方，52会下载的人多的是，没见你这么表现的，这是能往GitHub发的吗，别总是觉得自己高尚，别人就自私，自欺欺人吧了，别别人一捧你，让你干什么你就使劲表现。

我本来就是小白的水平，至于我发出来只要我不是抄袭的，我不用管别人怎么想吧？你这不就是自己觉得自己不发出来更高尚嘛，站在这个东西用的人多了就会影响别人的角度。

**Comment by 52beijixing** [comment]
> 我当时是在超理论坛公开的一个 python script [文章](https://chaoli.club/index.php/8554)，只不过有限制，而且那位 52poejie 大佬的文章直接用搜索引擎搜都能搜出来，写文章我还引用了一下。

我想实现epub下载的时候看到了那篇文章了，大佬确实没标注是畅想之星，不过能从图片里看出来是这个网站。

**Comment by ShiinaKaze** [comment]
> > 我当时是在超理论坛公开的一个 python script [文章](https://chaoli.club/index.php/8554)，只不过有限制，而且那位 52poejie 大佬的文章直接用搜索引擎搜都能搜出来，写文章我还引用了一下。
> 
> 我想实现epub下载的时候看到了那篇文章了，大佬确实没标注是畅想之星，不过能从图片里看出来是这个网站。

其实如果那个 52pojie 大佬发个文章，或者发邮件通知一下说建议不要这么做，我肯定会删除文章的。

**Comment by 52beijixing** [comment]
> > > 我当时是在超理论坛公开的一个 python script [文章](https://chaoli.club/index.php/8554)，只不过有限制，而且那位 52poejie 大佬的文章直接用搜索引擎搜都能搜出来，写文章我还引用了一下。
> > 
> > 
> > 我想实现epub下载的时候看到了那篇文章了，大佬确实没标注是畅想之星，不过能从图片里看出来是这个网站。
> 
> 其实如果那个 52pojie 大佬发个文章，或者发邮件通知一下说建议不要这么做，我肯定会删除文章的。

跟你其实没关系，我注册超理是因为那个科学文库的文章，但是点击技术板块，正好有你的文章，在看到你和大佬文章之前，我已经实现这个程序的，甚至在我注册超理之前，我已经上传到github了。
如果不是这么个人上来就说我抄袭，然后讽刺我啥的，好好的说的话，我应该会把项目私有，然后熟悉的人可以从我的蓝奏云下载。

**Comment by ShiinaKaze** [comment]
> > > > 我当时是在超理论坛公开的一个 python script [文章](https://chaoli.club/index.php/8554)，只不过有限制，而且那位 52poejie 大佬的文章直接用搜索引擎搜都能搜出来，写文章我还引用了一下。
> > > 
> > > 
> > > 我想实现epub下载的时候看到了那篇文章了，大佬确实没标注是畅想之星，不过能从图片里看出来是这个网站。
> > 
> > 
> > 其实如果那个 52pojie 大佬发个文章，或者发邮件通知一下说建议不要这么做，我肯定会删除文章的。
> 
> 跟你其实没关系，我注册超理是因为那个科学文库的文章，但是点击技术板块，正好有你的文章，在看到你和大佬文章之前，我已经实现这个程序的，甚至在我注册超理之前，我已经上传到github了。 如果不是这么个人上来就说我抄袭，然后讽刺我啥的，好好的说的话，我应该会把项目私有，然后熟悉的人可以从我的蓝奏云下载。

咱对逆向一无所知，老哥能写篇文章发在自己博客，谈谈怎样实现的么。

**Comment by 52beijixing** [comment]
> > > > > 我当时是在超理论坛公开的一个 python script [文章](https://chaoli.club/index.php/8554)，只不过有限制，而且那位 52poejie 大佬的文章直接用搜索引擎搜都能搜出来，写文章我还引用了一下。
> > > > 
> > > > 
> > > > 我想实现epub下载的时候看到了那篇文章了，大佬确实没标注是畅想之星，不过能从图片里看出来是这个网站。
> > > 
> > > 
> > > 其实如果那个 52pojie 大佬发个文章，或者发邮件通知一下说建议不要这么做，我肯定会删除文章的。
> > 
> > 
> > 跟你其实没关系，我注册超理是因为那个科学文库的文章，但是点击技术板块，正好有你的文章，在看到你和大佬文章之前，我已经实现这个程序的，甚至在我注册超理之前，我已经上传到github了。 如果不是这么个人上来就说我抄袭，然后讽刺我啥的，好好的说的话，我应该会把项目私有，然后熟悉的人可以从我的蓝奏云下载。
> 
> 咱对逆向一无所知，老哥能写篇文章发在自己博客，谈谈怎样实现的么。

这个不需要逆向啊，直接搜nonce就能找到算法的地方。
![1](https://github.com/52beijixing/cxstar-pdf-download/assets/75174838/46fd3b39-c58c-461f-a52b-b74c0a673d2d)

**Comment by 52beijixing** [comment]
> > > > > 我当时是在超理论坛公开的一个 python script [文章](https://chaoli.club/index.php/8554)，只不过有限制，而且那位 52poejie 大佬的文章直接用搜索引擎搜都能搜出来，写文章我还引用了一下。
> > > > 
> > > > 
> > > > 我想实现epub下载的时候看到了那篇文章了，大佬确实没标注是畅想之星，不过能从图片里看出来是这个网站。
> > > 
> > > 
> > > 其实如果那个 52pojie 大佬发个文章，或者发邮件通知一下说建议不要这么做，我肯定会删除文章的。
> > 
> > 
> > 跟你其实没关系，我注册超理是因为那个科学文库的文章，但是点击技术板块，正好有你的文章，在看到你和大佬文章之前，我已经实现这个程序的，甚至在我注册超理之前，我已经上传到github了。 如果不是这么个人上来就说我抄袭，然后讽刺我啥的，好好的说的话，我应该会把项目私有，然后熟悉的人可以从我的蓝奏云下载。
> 
> 咱对逆向一无所知，老哥能写篇文章发在自己博客，谈谈怎样实现的么。

这个说的比较详细点。至于这个项目，我写完epub下载之后肯定会私有的，月底私有，元旦写完epub公开一周，就这样吧！也不想跟他吵了

![1](https://github.com/52beijixing/cxstar-pdf-download/assets/75174838/123b4e50-c11e-4a5f-bf33-d1298a4592e5)

![2](https://github.com/52beijixing/cxstar-pdf-download/assets/75174838/1e9fa9a0-737a-492b-aff7-8f41bab3180d)

![3](https://github.com/52beijixing/cxstar-pdf-download/assets/75174838/401dc530-c43c-4a48-a486-b96fdf5f94d5)

**Comment by ShiinaKaze** [comment]
> > > > > > 我当时是在超理论坛公开的一个 python script [文章](https://chaoli.club/index.php/8554)，只不过有限制，而且那位 52poejie 大佬的文章直接用搜索引擎搜都能搜出来，写文章我还引用了一下。
> > > > > 
> > > > > 
> > > > > 我想实现epub下载的时候看到了那篇文章了，大佬确实没标注是畅想之星，不过能从图片里看出来是这个网站。
> > > > 
> > > > 
> > > > 其实如果那个 52pojie 大佬发个文章，或者发邮件通知一下说建议不要这么做，我肯定会删除文章的。
> > > 
> > > 
> > > 跟你其实没关系，我注册超理是因为那个科学文库的文章，但是点击技术板块，正好有你的文章，在看到你和大佬文章之前，我已经实现这个程序的，甚至在我注册超理之前，我已经上传到github了。 如果不是这么个人上来就说我抄袭，然后讽刺我啥的，好好的说的话，我应该会把项目私有，然后熟悉的人可以从我的蓝奏云下载。
> > 
> > 
> > 咱对逆向一无所知，老哥能写篇文章发在自己博客，谈谈怎样实现的么。
> 
> 这个说的比较详细点。至于这个项目，我写完epub下载之后肯定会私有的，月底私有，元旦写完epub公开一周，就这样吧！也不想跟他吵了
> 
> ![1](https://user-images.githubusercontent.com/75174838/283429770-123b4e50-c11e-4a5f-bf33-d1298a4592e5.png)
> 
> ![2](https://user-images.githubusercontent.com/75174838/283429804-1e9fa9a0-737a-492b-aff7-8f41bab3180d.png)
> 
> ![3](https://user-images.githubusercontent.com/75174838/283429841-401dc530-c43c-4a48-a486-b96fdf5f94d5.png)
OK, thanks

**Comment by ShiinaKaze** [comment]
> > > > > > 我当时是在超理论坛公开的一个 python script [文章](https://chaoli.club/index.php/8554)，只不过有限制，而且那位 52poejie 大佬的文章直接用搜索引擎搜都能搜出来，写文章我还引用了一下。
> > > > > 
> > > > > 
> > > > > 我想实现epub下载的时候看到了那篇文章了，大佬确实没标注是畅想之星，不过能从图片里看出来是这个网站。
> > > > 
> > > > 
> > > > 其实如果那个 52pojie 大佬发个文章，或者发邮件通知一下说建议不要这么做，我肯定会删除文章的。
> > > 
> > > 
> > > 跟你其实没关系，我注册超理是因为那个科学文库的文章，但是点击技术板块，正好有你的文章，在看到你和大佬文章之前，我已经实现这个程序的，甚至在我注册超理之前，我已经上传到github了。 如果不是这么个人上来就说我抄袭，然后讽刺我啥的，好好的说的话，我应该会把项目私有，然后熟悉的人可以从我的蓝奏云下载。
> > 
> > 
> > 咱对逆向一无所知，老哥能写篇文章发在自己博客，谈谈怎样实现的么。
> 
> 这个说的比较详细点。至于这个项目，我写完epub下载之后肯定会私有的，月底私有，元旦写完epub公开一周，就这样吧！也不想跟他吵了
> 
> ![1](https://user-images.githubusercontent.com/75174838/283429770-123b4e50-c11e-4a5f-bf33-d1298a4592e5.png)
> 
> ![2](https://user-images.githubusercontent.com/75174838/283429804-1e9fa9a0-737a-492b-aff7-8f41bab3180d.png)
> 
> ![3](https://user-images.githubusercontent.com/75174838/283429841-401dc530-c43c-4a48-a486-b96fdf5f94d5.png)

OK, thanks

**Comment by xrx128** [comment]
公开发确实会加快失效，但是上来就冤枉人说抄袭，这就是你的不对了，就不能好好说话吗

**Comment by zhubo** [comment]
这个脚本下载速度快，还集成书签，估计动了不少书贩和卖下载软件的蛋糕，遭人嫉恨了。再快的就只有破解客户端加密算法的了，直接下整本。
