### ISSUE TITLE
部分出版社下载有重复页

### ISSUE THREAD

**Issue by ayumi106** [52beijixing/cxstar-pdf-download#6]
2c88543000061eXXXX
比如上面的图书

**Comment by sci268** [comment]
非也，单个pdf就带了双页，所以只能手动删除重复页



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月10日 11:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [52beijixing/cxstar-pdf-download] 部分出版社下载有重复页 (Issue #6) |

2c88543000061eXXXX
比如上面的图书

**Comment by ayumi106** [comment]
但是文件下载总页数不全，因为是下载了重复页

**Comment by sci268** [comment]
我认为是文件本身的问题



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月10日 12:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [52beijixing/cxstar-pdf-download] 部分出版社下载有重复页 (Issue #6) |

但是文件下载总页数不全，因为是下载了重复页

**Comment by 52beijixing** [comment]
> 2c88543000061eXXXX 比如上面的图书

现在在外面，没电脑，一周后回家尝试复现和解决问题。

**Comment by 52beijixing** [comment]
> 非也，单个pdf就带了双页，所以只能手动删除重复页
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年11月10日 11:53 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | [52beijixing/cxstar-pdf-download] 部分出版社下载有重复页 (Issue #6) | 2c88543000061eXXXX 比如上面的图书 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

如果是仅仅该出版社单页pdf重复页的话应该可以解决的。

**Comment by ayumi106** [comment]
在线看的话，不存在重复的情况

**Comment by liuhanyou88** [comment]
下了电子、化学出版社的各一本，从版权页开始到最后都是重页只能手删，倒是没有缺页。用V1.04下载正常没有重复页

**Comment by 52beijixing** [comment]
> 下了电子、化学出版社的各一本，从版权页开始到最后都是重页只能手删，倒是没有缺页。用V1.04下载正常没有重复页

好的，谢谢，呢我就知道是哪里的问题了，晚上我让朋友用我的号改一下，提交新的代码和程序。

**Comment by 52beijixing** [comment]
> 2c88543000061eXXXX 比如上面的图书

尝试一下新的程序或者代码，应该解决这个问题了，朋友帮忙改了一下。

**Comment by 52beijixing** [comment]
朋友帮忙修改的时候忘了单个pdf不重复页的情况判定，代码及程序已更新。

如果7天内没有此类问题反馈，将会关闭此问题。

**Comment by liuhanyou88** [comment]
程序停留在 下载单页pdf中....... 一段时间后，报错闪退，没有合成PDF和加书签。所在目录有下载的单页pdf临时文件夹

**Comment by 52beijixing** [comment]
> 程序停留在 下载单页pdf中....... 一段时间后，报错闪退，没有合成PDF和加书签。所在目录有下载的单页pdf临时文件夹

你重新运行程序下载那本书试试，新版的不会覆盖原来下载的。我也遇到过这个问题，感觉是网络问题，后续确认后会添加容错机制。
